services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - ./local-files:/files
  gotenberg:
    image: gotenberg/gotenberg:8